name: can_i_go_out
description: App that check the corona enabled days by age and work status.

version: 1.2.7

module:
  androidX: true

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.1
  uuid: ^2.2.0
  path_provider: ^1.6.9
  dio: 2.0.22
  shared_preferences: 0.5.3+4
  flare_flutter: any
  flutter_webview_plugin: ^0.3.9+1
  wifi: ^0.1.5
  ping_discover_network: ^0.2.0+1
  rflutter_alert: ^1.0.3
  back_button_interceptor: ^4.2.1
  font_awesome_flutter: ^8.8.1
  flutter_secure_storage: ^3.3.3
  double_back_to_close_app: ^1.2.0
  pref_dessert: ^0.5.1
  flutter_cache_manager: ^1.2.2
  flutter_spinkit: ^4.1.2
  firebase_admob: ^0.9.3+4
  flutter_native_admob: ^2.1.0+3
  rxdart: ^0.24.1
  flutter_local_notifications: ^1.4.4+4
  permission_handler: ^5.0.1+1
  uni_links: ^0.4.0
  intl: ^0.16.1

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "can_i_go_out"
  ios: true
  image_path: "assets/icons/can_i_go_out/res/mipmap-xhdpi/can_i_go_out.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomFontIcons
      fonts:
        - asset: assets/fonts/CustomFontIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/locale/localization_de.json
    - assets/locale/localization_en.json
    - assets/locale/localization_es.json
    - assets/locale/localization_fr.json
    - assets/locale/localization_hi.json
    - assets/locale/localization_it.json
    - assets/locale/localization_kp.json
    - assets/locale/localization_tr.json
    - assets/icons/can_i_go_out/res/mipmap-xhdpi/can_i_go_out.png
    - assets/images/below_twenty.png
    - assets/images/above_sixty_five.png
    - assets/images/between_twenty-sixty_five.png
    - assets/images/has_work.png
